# Azure DevOps Pipeline for Logistics Application
# This pipeline builds and creates artifacts for all components of the logistics app

trigger:
  branches:
    include:
      - release
      - dev
  paths:
    exclude:
      - README.md
      - docs/*
      - '*.md'

pr:
  branches:
    include:
      - release
      - dev

variables:
  buildConfiguration: 'Release'
  dotNetVersion: '9.0.x'
  vmImageName: 'ubuntu-latest'
  PRESENTATION_PROJECTS_DIR: 'src/Presentation'
  CLIENT_PROJECTS_DIR: './src/Client'
  # Set to true to enable MAUI AOT steps in CI
  enableAot: false
  # Set this to true to enable Docker builds
  buildDockerImages: true

stages:
  - stage: 'Build'
    displayName: 'Build Applications'
    jobs:
      
       # Build Docker Images
      - job: 'BuildDockerImages'
        displayName: 'Build Docker Images'
        pool:
          vmImage: $(vmImageName)
        condition: eq(variables['buildDockerImages'], 'true')
          
        steps:
          - checkout: self
            fetchDepth: 1
            
          - task: Docker@2
            displayName: 'Build API Docker Image'
            inputs:
              containerRegistry: # Configure this with your container registry service connection
              repository: 'logistics-api'
              command: 'build'
              Dockerfile: 'src/Presentation/Logistics.API/Dockerfile'
              buildContext: '.'
              tags: |
                $(Build.BuildId)
                latest
                
          - task: Docker@2
            displayName: 'Build Identity Server Docker Image'  
            inputs:
              containerRegistry: # Configure this with your container registry service connection
              repository: 'logistics-identity'
              command: 'build'
              Dockerfile: 'src/Presentation/Logistics.IdentityServer/Dockerfile'
              buildContext: '.'
              tags: |
                $(Build.BuildId)
                latest
                
          - task: Docker@2
            displayName: 'Build Admin App Docker Image'
            inputs:
              containerRegistry: # Configure this with your container registry service connection  
              repository: 'logistics-admin'
              command: 'build'
              Dockerfile: 'src/Client/Logistics.AdminApp/Dockerfile'
              buildContext: '.'
              tags: |
                $(Build.BuildId)
                latest
            condition: exists('src/Client/Logistics.AdminApp/Dockerfile')
            
          # Save Docker images as artifacts
          - task: Docker@2
            displayName: 'Save API Docker Image'
            inputs:
              command: 'save'
              arguments: '-o $(Build.ArtifactStagingDirectory)/logistics-api.tar logistics-api:$(Build.BuildId)'
              
          - task: Docker@2
            displayName: 'Save Identity Docker Image'
            inputs:
              command: 'save'
              arguments: '-o $(Build.ArtifactStagingDirectory)/logistics-identity.tar logistics-identity:$(Build.BuildId)'
              
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Docker Images'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'docker-images'
      

  - stage: 'Test'
    displayName: 'Run Tests'
    dependsOn: 'Build'
    jobs:
      - job: 'RunTests'
        displayName: 'Run Unit Tests'
        pool:
          vmImage: $(vmImageName)
          
        steps:
          - checkout: self
            fetchDepth: 1
            
          - task: UseDotNet@2
            displayName: 'Setup .NET SDK'
            inputs:
              packageType: 'sdk'
              version: $(dotNetVersion)
              
          - task: DotNetCoreCLI@2
            displayName: 'Restore Test Dependencies'
            inputs:
              command: 'restore'
              projects: 'test/**/*.csproj'
              
          - task: DotNetCoreCLI@2
            displayName: 'Run Tests'
            inputs:
              command: 'test'
              projects: 'test/**/*.csproj'
              arguments: '--configuration $(buildConfiguration) --logger trx --collect:"XPlat Code Coverage"'
              publishTestResults: true
              
          - task: PublishCodeCoverageResults@1
            displayName: 'Publish Code Coverage'
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

  - stage: 'Package'
    displayName: 'Create Deployment Packages'
    dependsOn: ['Build', 'Test']
    jobs:
      - job: 'CreatePackages'
        displayName: 'Create Deployment Packages'
        pool:
          vmImage: $(vmImageName)
          
        steps:
          - download: current
            artifact: 'backend-services'
            displayName: 'Download Backend Artifacts'
            
          - download: current
            artifact: 'client-apps'
            displayName: 'Download Client App Artifacts'
            
          - download: current
            artifact: 'office-app'
            displayName: 'Download Office App Artifacts'
            condition: succeeded('BuildOfficeApp')
            
          - download: current
            artifact: 'mobile-app'  
            displayName: 'Download Mobile App Artifacts'
            
          - download: current
            artifact: 'docker-images'
            displayName: 'Download Docker Images'
            condition: and(succeeded(), eq(variables['buildDockerImages'], 'true'))
            
          - task: ArchiveFiles@2
            displayName: 'Create Complete Deployment Package'
            inputs:
              rootFolderOrFile: '$(Pipeline.Workspace)'
              includeRootFolder: true
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/logistics-app-complete-$(Build.BuildId).zip'
              
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Complete Package'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'deployment-package'